[theme]
primaryColor = "#4A90E2"  # 기본 버튼 및 상호작용 색상 (밝은 파란색)
backgroundColor = "#0E1117"  # 앱 전체 배경 (진한 회색)
secondaryBackgroundColor = "#1C202B" # 사이드바 및 컨테이너 배경 (조금 밝은 회색)
textColor = "#FAFAFA"  # 기본 텍스트 색상 (흰색)
font = "sans serif"  # 폰트